language: python

branches:
  only:
  - master
  - travic-ci-integration
  - /^\d+(\.\d+)+$/
on:
  tags: true

script:
- echo "TRAVIS_TAG is $TRAVIS_TAG"
- if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG > version.txt; fi

deploy:
  provider: pypi
  user: mdutkin
  password:
    secure: "yEP4C2OYRyhyjxCo4/6wcZCZ/DAYoAFsT9dkli3uK92571WCUbv4YTsgO+N6GPka7sv1/ll8VpwwNpdJmrOOqsLM84cdTVE1DB92qdkvK5TcSMXtBuAbpi7ttPOS1J/r0/QCy/2TxAgZCQA9SEGNjeGxnm19A5grE+r6qrdr+2PJwl4jUhCs49u3UQbWh1ua9JRqJJBzisDTy7y6B/VcBkt4oGos1MgRUyst9/SiFqrvGNkGFvhXRwXWnrajjAD7f2rqBLlSRRBYFRMKdODU5sE9b9BJVtqM1LzBud8VOvRzDPTH8N3RbUYl5SNRaRJ2HUTcacacAfYZAIxMRS6wQF66eSKMMGspVcBcTzwKbGSRokBBIZqAsP4z3kXgz8H6aCvT2j3d6XZQiH/Bs0IZxv513xSaHvTPtVR3H5XE4GlVSKnUZZ7uwmN1cmIlMszDf4oGRDgI5X3+unTlJgjpHzFoAvZhADUr/aFxh05wU9m4/xGGW518xCRjJvXxbLQDtZ3FJg9DV5CrggakH9oB68a2ajeLMi7LFHWRzMN3jiQO45drDAabc8MCDm2rWfKwAKLN1BHCoYqLxF5Yq9FkrOj2d+tNc6jYZoA2gZ4nLMvFCJQtePqNdCfBduR/HgI+a7HgbtT0YrF1eesupfXHPQ0TERgAR6CULJwUW//TVT8="
  on:
    tags: true
  skip_cleanup: true
  notifications:
    email:
      - max@dutkin.ru